// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQjtp3pxNPXIY1NCKFUw_UOqNLRyqETdg',
    appId: '1:261866755750:web:49ffbd943f26f04b648667',
    messagingSenderId: '261866755750',
    projectId: 'job-scrap-email-pro',
    authDomain: 'job-scrap-email-pro.firebaseapp.com',
    storageBucket: 'job-scrap-email-pro.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8Hv7Wrq8opap9KDxs5t7aH0uQ1MgK-l8',
    appId: '1:261866755750:android:323ece8d9924e8a2648667',
    messagingSenderId: '261866755750',
    projectId: 'job-scrap-email-pro',
    storageBucket: 'job-scrap-email-pro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2hrlbWI9b6qIuXIVGnuYiXniSU7AZAI4',
    appId: '1:261866755750:ios:1ac0247568e25cfa648667',
    messagingSenderId: '261866755750',
    projectId: 'job-scrap-email-pro',
    storageBucket: 'job-scrap-email-pro.firebasestorage.app',
    iosBundleId: 'com.example.jobScraper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2hrlbWI9b6qIuXIVGnuYiXniSU7AZAI4',
    appId: '1:261866755750:ios:1ac0247568e25cfa648667',
    messagingSenderId: '261866755750',
    projectId: 'job-scrap-email-pro',
    storageBucket: 'job-scrap-email-pro.firebasestorage.app',
    iosBundleId: 'com.example.jobScraper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQjtp3pxNPXIY1NCKFUw_UOqNLRyqETdg',
    appId: '1:261866755750:web:425156f945e2cfe4648667',
    messagingSenderId: '261866755750',
    projectId: 'job-scrap-email-pro',
    authDomain: 'job-scrap-email-pro.firebaseapp.com',
    storageBucket: 'job-scrap-email-pro.firebasestorage.app',
  );
}
